flowchart TD

    %% Node definitions
    company_1["Google Inc"]
    risk_1("cybersecurity risks")
    amount_1[/"$300 billion"/]
    company_2["Google LLC"]
    risk_2("content moderation risks")
    amount_2[/"$30 billion"/]

    %% Relationships
    company_1 -->|HAS_RISK| risk_1
    company_1 -->|REPORTS_AMOUNT| amount_1
    company_1 -->|OWNS| company_2
    company_1 -->|HAS_RISK| risk_2
